---
  - hosts: all
    remote_user: vagrant
    sudo: true
    tasks:
      - name: install packages
        apt: name={{ item }} update_cache=yes state=latest
        with_items:
          - git
          - mcrypt
          - nginx
          - php5-cli
          - php5-curl
          - php5-fpm
          - php5-intl
          - php5-json
          - php5-mcrypt
          - php5-sqlite
          - sqlite3

      - name: ensure php5-fpm cgi.fix_pathinfo=0
        lineinfile: dest=/etc/php5/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
        notify:
          - restart php5-fpm
          - restart nginx

      - name: create /var/www/ directory
        file: dest=/var/www/ state=directory owner=www-data group=www-data mode=0700

    handlers:
      - name: restart php5-fpm
        service: name=php5-fpm state=restarted

      - name: restart nginx
        service: name=nginx state=restarted
